services:
  primary:
    build: Primary/
    command: flask run
    ports:
      - 5000:5000

  secondary_frst:
    build: secondary_frst/
    command: python ./secondary.py
    ports:
      - 6000:6000


    depends_on:
      - primary
